package com.lance.model;

import com.lance.core.open.BaseApplicationModuleImpl;
import com.lance.model.vo.URoleVOImpl;
import com.lance.model.vo.UUserRoleVOImpl;
import com.lance.model.vo.UUserVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 05 16:33:08 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Lance1AMImpl extends BaseApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Lance1AMImpl() {
    }

    /**
     * Container's getter for URole1.
     * @return URole1
     */
    public URoleVOImpl getURole1() {
        return (URoleVOImpl) findViewObject("URole1");
    }

    /**
     * Container's getter for UUserRole1.
     * @return UUserRole1
     */
    public UUserRoleVOImpl getUUserRole1() {
        return (UUserRoleVOImpl) findViewObject("UUserRole1");
    }

    /**
     * Container's getter for UUser1.
     * @return UUser1
     */
    public UUserVOImpl getUUser1() {
        return (UUserVOImpl) findViewObject("UUser1");
    }
}

