package com.lance.model.vo;

import com.lance.core.open.BaseViewRowImpl;
import com.lance.model.eo.URoleEOImpl;
import com.lance.model.eo.common.Text;

import java.math.BigDecimal;

import java.sql.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 05 16:32:14 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class URoleVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_UROLEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Nid,
        Name,
        CnName,
        PriviledgeDesc,
        CreatedBy,
        CreatedOn,
        UpdatedBy,
        UpdatedOn,
        Version;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int NID = AttributesEnum.Nid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int CNNAME = AttributesEnum.CnName.index();
    public static final int PRIVILEDGEDESC = AttributesEnum.PriviledgeDesc.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDON = AttributesEnum.UpdatedOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public URoleVORowImpl() {
    }

    /**
     * Gets URoleEO entity object.
     * @return the URoleEO
     */
    public URoleEOImpl getURoleEO() {
        return (URoleEOImpl) getEntity(ENTITY_UROLEEO);
    }

    /**
     * Gets the attribute value for NID using the alias name Nid.
     * @return the NID
     */
    public Integer getNid() {
        return (Integer) getAttributeInternal(NID);
    }

    /**
     * Sets <code>value</code> as attribute value for NID using the alias name Nid.
     * @param value value to set the NID
     */
    public void setNid(Integer value) {
        setAttributeInternal(NID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for CN_NAME using the alias name CnName.
     * @return the CN_NAME
     */
    public String getCnName() {
        return (String) getAttributeInternal(CNNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CN_NAME using the alias name CnName.
     * @param value value to set the CN_NAME
     */
    public void setCnName(String value) {
        setAttributeInternal(CNNAME, value);
    }

    /**
     * Gets the attribute value for PRIVILEDGE_DESC using the alias name PriviledgeDesc.
     * @return the PRIVILEDGE_DESC
     */
    public Text getPriviledgeDesc() {
        return (Text) getAttributeInternal(PRIVILEDGEDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIVILEDGE_DESC using the alias name PriviledgeDesc.
     * @param value value to set the PRIVILEDGE_DESC
     */
    public void setPriviledgeDesc(Text value) {
        setAttributeInternal(PRIVILEDGEDESC, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_ON using the alias name CreatedOn.
     * @return the CREATED_ON
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_ON using the alias name CreatedOn.
     * @param value value to set the CREATED_ON
     */
    public void setCreatedOn(Timestamp value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_ON using the alias name UpdatedOn.
     * @return the UPDATED_ON
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) getAttributeInternal(UPDATEDON);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_ON using the alias name UpdatedOn.
     * @param value value to set the UPDATED_ON
     */
    public void setUpdatedOn(Timestamp value) {
        setAttributeInternal(UPDATEDON, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public Integer getVersion() {
        return (Integer) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(Integer value) {
        setAttributeInternal(VERSION, value);
    }
}

