package com.lance.model.eo;

import com.lance.core.open.BaseEntityImpl;
import com.lance.model.eo.common.Text;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 05 16:31:25 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class URoleEOImpl extends BaseEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Nid,
        Name,
        CnName,
        PriviledgeDesc,
        CreatedBy,
        CreatedOn,
        UpdatedBy,
        UpdatedOn,
        Version;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int NID = AttributesEnum.Nid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int CNNAME = AttributesEnum.CnName.index();
    public static final int PRIVILEDGEDESC = AttributesEnum.PriviledgeDesc.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDON = AttributesEnum.UpdatedOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public URoleEOImpl() {
    }

    /**
     * Gets the attribute value for Nid, using the alias name Nid.
     * @return the value of Nid
     */
    public Integer getNid() {
        return (Integer) getAttributeInternal(NID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nid.
     * @param value value to set the Nid
     */
    public void setNid(Integer value) {
        setAttributeInternal(NID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for CnName, using the alias name CnName.
     * @return the value of CnName
     */
    public String getCnName() {
        return (String) getAttributeInternal(CNNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnName.
     * @param value value to set the CnName
     */
    public void setCnName(String value) {
        setAttributeInternal(CNNAME, value);
    }

    /**
     * Gets the attribute value for PriviledgeDesc, using the alias name PriviledgeDesc.
     * @return the value of PriviledgeDesc
     */
    public Text getPriviledgeDesc() {
        return (Text) getAttributeInternal(PRIVILEDGEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for PriviledgeDesc.
     * @param value value to set the PriviledgeDesc
     */
    public void setPriviledgeDesc(Text value) {
        setAttributeInternal(PRIVILEDGEDESC, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedOn.
     * @param value value to set the CreatedOn
     */
    public void setCreatedOn(Timestamp value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public BigDecimal getUpdatedBy() {
        return (BigDecimal) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(BigDecimal value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedOn, using the alias name UpdatedOn.
     * @return the value of UpdatedOn
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) getAttributeInternal(UPDATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedOn.
     * @param value value to set the UpdatedOn
     */
    public void setUpdatedOn(Timestamp value) {
        setAttributeInternal(UPDATEDON, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public Integer getVersion() {
        return (Integer) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Integer value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * @param nid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer nid) {
        return new Key(new Object[] { nid });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.lance.model.eo.URoleEO");
    }
}

